language: csharp
mono: none
dist: trusty
sudo: required
dotnet: 2.1.500
script:
 - dotnet restore
 - dotnet build -c Release BorderArc.Redis /m:1
after_success:
  script: chmod +x ./.ci/aftersuccess.sh && ./.ci/aftersuccess.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DOCS $PROJECT_DIR_ABS