language: csharp
solution: BorderArc.Redis.sln
mono: none
before_install:
  - sudo apt-get update```
sudo: required
dist: trusty
dotnet: 2.1.500
script:
 - dotnet restore
 - dotnet build -c Release BorderArc.Redis /m:1


